CREATE SEQUENCE autoPlayer_ID
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE autoPartida_ID
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1;

CREATE OR REPLACE TRIGGER PLAYERS_INSERT
BEFORE INSERT ON PLAYERS
FOR EACH ROW
BEGIN
    IF :NEW.ID_P = 0 THEN
        :NEW.ID_P := autoPlayer_ID.NEXTVAL;
    END IF;
END;

CREATE OR REPLACE TRIGGER PARTIDA_INSERT
BEFORE INSERT ON PARTIDA
FOR EACH ROW
BEGIN
    IF :NEW.ID_P = 0 THEN
        :NEW.ID_P := autoPlayer_ID.NEXTVAL;
    END IF;
END;

CREATE TABLE PARTIDA (
ID_PARTIDA NUMBER(5) PRIMARY KEY,
ID_P NUMBER(5),
DIFICULTAD NUMBER(5),
RONDAS NUMBER(5),
ACCIONES NUMBER(5),
BROTES NUMBER(5),
ARRAY_CIUDADES ARRAY_CIUDADES,
ARRAY_VACUNAS ARRAY_VACUNAS,
WL VARCHAR2(5),
FOREIGN KEY (ID_P) REFERENCES PLAYERS (ID_P));


CREATE OR REPLACE TYPE ARRAY_CIUDADES AS VARRAY (48) OF CIUDADES;
CREATE OR REPLACE TYPE ARRAY_VACUNAS AS VARRAY (4) OF VACUNAS;

DROP TYPE ARRAY_CIUDADES;
DROP TYPE ARRAY_VACUNAS;

DROP SEQUENCE autoPlayer_ID;
DROP SEQUENCE autoPartida_ID;

DROP TABLE PARTIDA;
DELETE FROM PLAYERS;

SELECT p.id_p, p.id_partida, p.dificultad, p.rondas, p.acciones, p.brotes, p.wl, c.nombre, c.infeccion
FROM PARTIDA p, TABLE(p.ARRAY_CIUDADES) c
WHERE ID_PARTIDA = 1;








